### ISSUE TITLE
reproduce environment?

### ISSUE THREAD

**Issue by edangx101** [microsoft/NeMoEval#4]
Hi, i was using Ubuntu in WSL2 Win11 environment. I was not able to reproduce the environment listed in 'requirements.txt'.  Many of packages like bzip2 for example is not available.

**Comment by lesleychou** [comment]
Hi, thank you for raising the issue!
Please check the latest 'requirements.txt' under branch "[update-2](https://github.com/microsoft/NeMoEval/tree/update-2)".
