### ISSUE TITLE
pip install error 

### ISSUE THREAD

**Issue by y1lan** [microsoft/NeMoEval#5]
I am trying to build the virtual environment of the project. But when I execute the command --
```
pip install -r requirements.txt
```

then it  throws me an error:

```
ERROR: Invalid requirement: 'aiohttp=3.8.4=pypi_0' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```

which indicates that there is syntax error in "requirement.txt" file. 

I am not familiar with the toolkits like  "conda, python, pip", maybe it is easy to fix up. But I hope I could  get some help.

My working environment is as follows:

os: archlinux with kernel 6.5.7;

conda: version 23.7.4;

python: version 3.11.5;

pip: version 23.3.1;

**Comment by lesleychou** [comment]
Thank you for raising the issue! 
Please check the latest 'requirements.txt' under branch "[update-2](https://github.com/microsoft/NeMoEval/tree/update-2)".
