### ISSUE TITLE
requirments.txt need to be updated in the main branch

### ISSUE THREAD

**Issue by Temo27anas** [microsoft/NeMoEval#7]
requirments.txt need to be updated in the main branch,
it creates the [ ERROR: Invalid requirement: 'aiohttp=3.8.4=pypi_0' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ? ]  issue

**Comment by kevinhsieh** [comment]
Thanks for the comment! This is addressed in the latest main branch.
